#!/usr/bin/env python3
"""LifeOS vault CLI — everything mechanical about the vault.

The determinism boundary lives here. Judgment (what a source means, whether an
inbox item is a project, which wiki page to update) belongs to a human or a model.
Naming, validation, link integrity, generated views, and status arithmetic are this
script's job, and it never interprets note content as instructions.

    python3 scripts/vault.py check        structure + schema + generated freshness
    python3 scripts/vault.py lint         frontmatter only
    python3 scripts/vault.py links        broken wikilinks (--wanted: most-wanted pages)
    python3 scripts/vault.py index        regenerate Home.md and the indexes
    python3 scripts/vault.py status       what needs attention (--json for agents)
    python3 scripts/vault.py tasks        open checkboxes across the vault
    python3 scripts/vault.py doctor       check + advisory health report
    python3 scripts/vault.py new <type> "<Title>" [--set k=v]
    python3 scripts/vault.py rename <path> "<New Title>"   (--dry-run first)
    python3 scripts/vault.py docs         regenerate docs/schema.md from config

Stdlib only. Every write is atomic (temp file + rename) and every generator is
idempotent: running a command twice changes nothing the first run did not.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import frontmatter as fmlib
import lint_frontmatter as linter
from lifeos_config import VAULT, Config, ConfigError, load

GENERATED_MARK = ("<!-- GENERATED by `python3 scripts/vault.py index` — "
                  "edit the source notes, not this file -->")

# Characters that break `[[wikilinks]]` or are illegal on some filesystems.
HARD_ILLEGAL = set('/\\|')
SOFT_ILLEGAL = set('#^[]:*?"<>')

NAME_PATTERNS = {
    "dated": re.compile(r"^\d{4}-\d{2}-\d{2} .+\.md$"),
    "daily": re.compile(r"^\d{4}-\d{2}-\d{2}\.md$"),
    "week": re.compile(r"^\d{4}-W\d{2}\.md$"),
    "log": re.compile(r"^\d{4}-\d{2}-\d{2}-[a-z0-9]+(?:-[a-z0-9]+)*\.md$"),
    "capture": re.compile(r"^\d{4}-\d{2}-\d{2} \d{4} .+\.md$"),
}
DATE_PREFIX_RE = re.compile(r"^\d{4}-\d{2}-\d{2}[ -]")
TASK_OPEN_RE = re.compile(r"^\s*[-*] \[ \] (.+)$", re.MULTILINE)
TASK_DONE_RE = re.compile(r"^\s*[-*] \[[xX]\] ", re.MULTILINE)


# ------------------------------------------------------------------ helpers

rel = linter.rel

# A single `check` reads every note for the linter, the structure pass, the link
# graph, and index regeneration. Caching the read and the parse turns four passes
# over the disk into one; the cache is invalidated on write, and the process is
# short-lived, so it cannot go stale.
_TEXT_CACHE: dict[str, str] = {}
_FM_CACHE: dict[str, object] = {}


def read_text(p: Path) -> str:
    key = str(p)
    cached = _TEXT_CACHE.get(key)
    if cached is None:
        try:
            cached = p.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            cached = ""
        _TEXT_CACHE[key] = cached
    return cached


def atomic_write(p: Path, text: str) -> None:
    """Write via a temp file in the same directory, then rename. A crash mid-write
    leaves the previous version intact rather than a truncated note."""
    p.parent.mkdir(parents=True, exist_ok=True)
    tmp = p.with_suffix(p.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(p)
    _TEXT_CACHE.pop(str(p), None)
    _FM_CACHE.pop(str(p), None)


def iter_notes(cfg: Config, dirs=None):
    yield from linter.iter_notes(cfg, dirs)


def parse_note(p: Path):
    key = str(p)
    cached = _FM_CACHE.get(key)
    if cached is None:
        cached = fmlib.parse(read_text(p))
        _FM_CACHE[key] = cached
    return cached


def fm_str(value) -> str:
    if isinstance(value, list):
        return ", ".join(str(v) for v in value)
    return str(value).strip('"') if value is not None else ""


def parse_date(value) -> dt.date | None:
    s = fmlib.unquote(str(value or "")).strip()
    try:
        return dt.date.fromisoformat(s[:10])
    except ValueError:
        return None


def days_since(value, today: dt.date) -> int | None:
    d = parse_date(value)
    return (today - d).days if d else None


# Most filesystems cap a single name at 255 bytes. Leave room for a date prefix, a
# collision suffix, the extension, and the `.tmp` an atomic write appends.
MAX_STEM_BYTES = 180


def slugify(title: str) -> str:
    """Make a filename from a title: drop link-unsafe characters, cap the length.

    The full, pretty title is never lost — it stays in `title:` and is added to
    `aliases:` whenever it differs, so `[[The Original Title]]` still resolves.
    """
    out = "".join("-" if ch in HARD_ILLEGAL else ("" if ch in SOFT_ILLEGAL else ch)
                  for ch in title)
    out = re.sub(r"-{2,}", "-", re.sub(r"\s+", " ", out)).strip(" .-")

    if len(out.encode("utf-8")) > MAX_STEM_BYTES:
        # Cut on a word boundary where possible, and never mid-character.
        truncated = out.encode("utf-8")[:MAX_STEM_BYTES].decode("utf-8", "ignore")
        head, _, _ = truncated.rpartition(" ")
        out = (head or truncated).strip(" .-")
    return out or "Untitled"


def next_free_path(p: Path, limit: int = 100) -> Path:
    if not p.exists():
        return p
    for n in range(2, limit):
        cand = p.with_name(f"{p.stem} {n}{p.suffix}")
        if not cand.exists():
            return cand
    raise SystemExit(f"too many files named like {p.name}")


def basename_index(cfg: Config) -> dict[str, list[Path]]:
    """Title (and alias) -> files. Wikilinks resolve by basename, never by path."""
    idx: dict[str, list[Path]] = defaultdict(list)
    for p in iter_notes(cfg):
        idx[p.stem].append(p)
        fm = parse_note(p)
        for alias in fmlib.as_list(fm.get("aliases")):
            idx[fmlib.unquote(str(alias))].append(p)
    return idx


def note_type(cfg: Config, p: Path):
    return cfg.type_for_path(rel(p))


# ------------------------------------------------------------------ structure

def structure_issues(cfg: Config) -> tuple[list[str], list[str]]:
    """Filenames and folders. Returns (errors, warnings)."""
    errors: list[str] = []
    warnings: list[str] = []
    for p in iter_notes(cfg):
        r = rel(p)
        if p.name.startswith("_") or cfg.is_generated(r):
            continue
        ntype = cfg.type_for_path(r)
        if ntype is None:
            continue

        bad_hard = {ch for ch in p.stem if ch in HARD_ILLEGAL}
        if bad_hard:
            errors.append(f"{r}: filename contains {''.join(sorted(bad_hard))!r} — breaks links")
        bad_soft = {ch for ch in p.stem if ch in SOFT_ILLEGAL}
        if bad_soft:
            warnings.append(
                f"{r}: filename contains {''.join(sorted(bad_soft))!r} — links to it may not "
                f"resolve (fix: vault.py rename)")

        pattern = ntype.filename
        variant = cfg.variant_for_path(r)
        if variant and variant.filename:
            pattern = variant.filename

        if pattern == "title":
            if DATE_PREFIX_RE.match(p.name):
                errors.append(f"{r}: evergreen {ntype.name} notes are not date-prefixed")
        elif pattern == "daily":
            if not (NAME_PATTERNS["daily"].match(p.name)
                    and re.match(rf"^{ntype.folder}/\d{{4}}/\d{{2}}/", r)):
                errors.append(f"{r}: expected {ntype.folder}/YYYY/MM/YYYY-MM-DD.md")
        elif pattern == "week":
            if not (NAME_PATTERNS["week"].match(p.name) or NAME_PATTERNS["dated"].match(p.name)):
                errors.append(f"{r}: expected 'YYYY-Www.md' or 'YYYY-MM-DD Title.md'")
        elif pattern == "capture":
            if not NAME_PATTERNS["capture"].match(p.name):
                warnings.append(f"{r}: captures are usually named 'YYYY-MM-DD HHmm Title.md'")
        elif pattern in NAME_PATTERNS:
            if not NAME_PATTERNS[pattern].match(p.name):
                hint = {"dated": "YYYY-MM-DD Title.md",
                        "log": "YYYY-MM-DD-<run_type>.md"}[pattern]
                errors.append(f"{r}: expected '{hint}'")

        # A type with variants must file its notes into one of them.
        if ntype.variants and variant is None and not cfg.is_generated(r):
            errors.append(f"{r}: {ntype.name} notes live in "
                          f"{ntype.folder}/<{'|'.join(ntype.subfolders)}>/")

        # Folders are a closed set (docs/routing.md): navigation is links, not
        # hierarchy. An undeclared subfolder is drift, and it is invisible until
        # someone wonders why half their projects are missing from a view.
        declared = set(ntype.subfolders)
        if ntype.archive_folder:
            declared.add(ntype.archive_folder.split("/", 1)[1])
        depth = r[len(ntype.folder) + 1:].count("/")
        if depth and ntype.filename != "daily":
            sub = r[len(ntype.folder) + 1:].rsplit("/", 1)[0]
            if sub not in declared:
                warnings.append(
                    f"{r}: {ntype.folder}/{sub}/ is not a declared subfolder. "
                    f"Folders are a closed set — link the note instead, or add a "
                    f"variant in config/lifeos.toml.")
    return errors, warnings


# ------------------------------------------------------------------ links

def link_report(cfg: Config):
    """Wikilinks that resolve to nothing. Returns (counter, examples)."""
    idx = basename_index(cfg)
    broken: Counter = Counter()
    where: dict[str, list[str]] = defaultdict(list)
    for p in iter_notes(cfg):
        r = rel(p)
        if r.startswith("logs/"):
            continue  # audit trail may reference notes that were later renamed
        text = fmlib.strip_code(read_text(p))
        for raw in set(fmlib.INLINE_LINK_RE.findall(text)):
            target = fmlib.link_target(raw)
            if not target or target in idx:
                continue
            broken[target] += 1
            if len(where[target]) < 3:
                where[target].append(r)
    return broken, where


def duplicate_basenames(cfg: Config) -> list[str]:
    """Two notes with the same filename make every `[[link]]` to them ambiguous:
    Obsidian silently picks one. Catch it at the moment it is created."""
    seen: dict[str, list[str]] = defaultdict(list)
    for p in iter_notes(cfg):
        # `_`-prefixed files are registries and generated indexes. Every folder has
        # its own `_index.md` by design; each carries a unique alias, and nothing
        # links to them by basename.
        if p.name.startswith("_"):
            continue
        seen[p.stem].append(rel(p))
    return [f"duplicate note name [[{stem}]] — links to it are ambiguous: "
            + ", ".join(sorted(paths))
            for stem, paths in sorted(seen.items()) if len(paths) > 1]


def source_link_issues(cfg: Config) -> tuple[list[str], list[str]]:
    """Every wiki `sources:` entry must resolve to a note under the source folder.
    Provenance is the wiki's whole claim to trustworthiness, so a source pointing at
    a non-source note is an error, while one pointing at nothing is a review queue."""
    stype = cfg.types.get("source")
    wtype = cfg.types.get("wiki")
    if not stype or not wtype:
        return [], []
    idx = basename_index(cfg)
    errors: list[str] = []
    dangling: list[str] = []
    for p in iter_notes(cfg, [wtype.folder]):
        r = rel(p)
        if cfg.is_generated(r) or p.name.startswith("_"):
            continue
        for entry in fmlib.as_list(parse_note(p).get("sources")):
            target = fmlib.link_target(str(entry))
            hits = idx.get(target)
            if not hits:
                dangling.append(f"{r}: sources entry [[{target}]] resolves to nothing")
            elif not any(rel(h).startswith(stype.folder + "/") for h in hits):
                errors.append(f"{r}: sources entry [[{target}]] is not under {stype.folder}/")
    return errors, dangling


# ------------------------------------------------------------------ generated views

def _index_frontmatter(cfg: Config, title: str, created: str, updated: str) -> list[str]:
    # Every generated index is named `_index.md` in its own folder, which is the
    # Obsidian convention for "sorts first" — but it makes `[[_index]]` ambiguous.
    # The alias gives each one a unique, linkable name.
    return ["---", "type: wiki", f'title: "{title}"', f'aliases: ["{title}"]',
            f'created: "{created}"', f'updated: "{updated}"',
            f"domain: {cfg.meta_domain}", "tags: [index]", "---", GENERATED_MARK, ""]


def _collect(cfg: Config, folder: str, skip_generated: bool = True):
    for p in iter_notes(cfg, [folder]):
        r = rel(p)
        if p.name.startswith("_") or (skip_generated and cfg.is_generated(r)):
            continue
        yield p, parse_note(p)


def gen_projects_index(cfg: Config, today: dt.date) -> str:
    ptype = cfg.types["project"]
    statuses = ptype.enums.get("status", ["active"])
    rows: dict[str, list] = {s: [] for s in statuses}
    latest = ""
    for p, fm in _collect(cfg, ptype.folder):
        status = fm_str(fm.get("status")) or statuses[0]
        rows.setdefault(status, []).append((p.stem, fm))
        latest = max(latest, fm_str(fm.get("updated")))

    lines = _index_frontmatter(cfg, "Projects Index", "2026-01-01",
                               latest or today.isoformat())
    lines += ["# Projects Index", "",
              "One line per project, grouped by status. Live view: `bases/projects.base`.",
              f"Lifecycle: {' → '.join(statuses)} (docs/routing.md).", ""]
    for status in statuses:
        items = sorted(rows.get(status, []),
                       key=lambda t: (fm_str(t[1].get("updated")), t[0]), reverse=True)
        lines += [f"## {status.title()} ({len(items)})", ""]
        if not items:
            lines.append("- (none)")
        for stem, fm in items:
            question = fm_str(fm.get("question")).strip()
            meta = " · ".join(x for x in (
                fm_str(fm.get("domain")), fm_str(fm.get("kind")),
                f"updated {fm_str(fm.get('updated'))}" if fm.get("updated") else "") if x)
            lines.append(f"- [[{stem}]] — {question}" + (f" _({meta})_" if meta else ""))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _wiki_hook(fm, body: str) -> str:
    """One line describing a wiki page: its first real sentence, capped."""
    for line in body.splitlines():
        s = line.strip()
        if not s or s.startswith(("#", "-", ">", "|", "<!--", "```")):
            continue
        s = re.sub(r"\[\[([^\[\]|]+)(?:\|[^\[\]]*)?\]\]", r"\1", s)
        s = re.sub(r"[*_`]", "", s)
        return (s[:117] + "…") if len(s) > 118 else s
    return ""


def gen_wiki_domain_pages(cfg: Config, today: dt.date) -> dict[str, str]:
    """One router page per domain. Splitting the router up front is the scaling
    migration the source vault deferred: at 2,000 pages a single index becomes too
    large to read, and by then it is load-bearing."""
    wtype = cfg.types["wiki"]
    by_domain: dict[str, list] = defaultdict(list)
    for p, fm in _collect(cfg, wtype.folder):
        r = rel(p)
        if r.startswith(cfg.wiki_domain_dir + "/"):
            continue
        domain = fm_str(fm.get("domain")) or "unsorted"
        by_domain[domain].append((p, fm))

    out: dict[str, str] = {}
    for domain in cfg.domains:
        items = sorted(by_domain.get(domain, []), key=lambda t: t[0].stem.lower())
        latest = max((fm_str(fm.get("updated")) for _, fm in items), default="")
        lines = _index_frontmatter(cfg, f"{domain.title()} Domain", "2026-01-01",
                                   latest or today.isoformat())
        lines += [f"# {domain.title()}", "",
                  f"Every wiki page with `domain: {domain}`. Regenerated by `vault.py index`.", ""]
        # Prose above the marker survives regeneration; see _preserve_prose.
        lines += ["<!-- PROSE:START --><!-- PROSE:END -->", "",
                  f"## Pages ({len(items)})", ""]
        if not items:
            lines.append("- (none yet)")
        for p, fm in items:
            hook = _wiki_hook(fm, fmlib.parse(read_text(p)).body)
            lines.append(f"- [[{p.stem}]]" + (f" — {hook}" if hook else ""))
        out[f"{cfg.wiki_domain_dir}/{domain}.md"] = "\n".join(lines).rstrip() + "\n"
    return out


def gen_wiki_index(cfg: Config, today: dt.date) -> str:
    """A dispatcher, not a catalogue. Agents grep this, then open one domain page,
    or skip it entirely and use `retrieve.py`."""
    wtype = cfg.types["wiki"]
    counts: Counter = Counter()
    recent: list[tuple[str, str]] = []
    for p, fm in _collect(cfg, wtype.folder):
        r = rel(p)
        if r.startswith(cfg.wiki_domain_dir + "/"):
            continue
        counts[fm_str(fm.get("domain")) or "unsorted"] += 1
        recent.append((fm_str(fm.get("updated")), p.stem))
    total = sum(counts.values())
    lines = _index_frontmatter(cfg, "Wiki Index", "2026-01-01", today.isoformat())
    lines += [
        "# Wiki Index", "",
        f"{total} compiled pages. This file is a **router**, not a catalogue.", "",
        "- Looking for a topic? `python3 scripts/retrieve.py \"<query>\"` searches page text.",
        "- Browsing by area of life? Open the domain page below.",
        "- Need an exact title? `grep -r '^title:' wiki/`.", "",
        "## Domains", "",
    ]
    for domain in cfg.domains:
        n = counts.get(domain, 0)
        lines.append(f"- [[{domain}]] — {n} page{'s' if n != 1 else ''}")
    unsorted = counts.get("unsorted", 0)
    if unsorted:
        lines.append(f"- _(unsorted: {unsorted} page(s) with no domain — `vault doctor` lists them)_")
    lines += ["", "## Recently updated", ""]
    for _, stem in sorted((r for r in recent if r[0]), reverse=True)[:15]:
        lines.append(f"- [[{stem}]]")
    if not recent:
        lines.append("- (none yet)")
    return "\n".join(lines).rstrip() + "\n"


def gen_home(cfg: Config, today: dt.date) -> str:
    """The landing page. Deliberately small and stable: counts, what needs attention,
    and links to the live Base views. It is a signpost, not a data dump."""
    st = collect_status(cfg, today)
    lines = ["---", "type: wiki", 'title: "Home"', 'created: "2026-01-01"',
             f'updated: "{today.isoformat()}"', f"domain: {cfg.meta_domain}",
             "tags: [index]", "---", GENERATED_MARK, "",
             f"# {cfg.name}", "",
             f"_Regenerated {today.isoformat()} by `python3 scripts/vault.py index`._", "",
             "## Needs attention", ""]

    bullets = []
    if st["inbox"]["count"]:
        oldest = st["inbox"]["oldest_days"]
        bullets.append(f"**Inbox:** {st['inbox']['count']} item(s)"
                       + (f", oldest {oldest}d" if oldest is not None else ""))
    for label, items in (("Stale active projects", st["projects"]["stale"]),
                         ("Old ideas", st["projects"]["old_ideas"]),
                         ("Projects awaiting archive", st["projects"]["awaiting_archive"]),
                         ("Decisions due for outcome", st["decisions"]["due"])):
        if items:
            bullets.append(f"**{label}:** " + ", ".join(f"[[{i}]]" for i in items[:6])
                           + (" …" if len(items) > 6 else ""))
    if st["tasks"]["open"]:
        bullets.append(f"**Open tasks:** {st['tasks']['open']} across "
                       f"{st['tasks']['notes']} note(s) — `vault.py tasks`")
    lines += [f"- {b}" for b in bullets] or ["- Nothing. Good."]

    lines += ["", "## Counts", "", "| What | Count |", "|---|---|"]
    for label, value in (("Projects active", st["projects"]["by_status"].get("active", 0)),
                         ("Projects total", sum(st["projects"]["by_status"].values())),
                         ("Areas active", st["areas"]["active"]),
                         ("Wiki pages", st["wiki"]["total"]),
                         ("Sources", st["sources"]["total"]),
                         ("People", st["people"]), ("Meetings", st["meetings"])):
        lines.append(f"| {label} | {value} |")

    lines += ["", "## Views", "",
              "Open these in Obsidian for live tables:", "",
              "- `bases/attention.base` — everything waiting on you",
              "- `bases/projects.base` — projects by status",
              "- `bases/knowledge.base` — wiki pages and sources",
              "- `bases/people.base` — people and meetings", "",
              "## Indexes", "",
              "- [[Projects Index]] · every project, grouped by status",
              "- [[Wiki Index]] · the router into compiled knowledge", "",
              "## Start here", "",
              "- `AGENTS.md` — the map, the invariants, the commands",
              "- `docs/daily-guide.md` — how to actually use this day to day",
              "- `docs/routing.md` — where does this note go?", ""]
    return "\n".join(lines).rstrip() + "\n"


PROSE_RE = re.compile(r"<!-- PROSE:START -->(.*?)<!-- PROSE:END -->", re.DOTALL)


def _preserve_prose(old: str, new: str) -> str:
    """Carry a human-written preamble across regeneration. Generated files are
    otherwise fully owned by the generator; this is the one sanctioned exception,
    and it is explicitly delimited so nobody has to guess."""
    m_old, m_new = PROSE_RE.search(old), PROSE_RE.search(new)
    if not (m_old and m_new) or not m_old.group(1).strip():
        return new
    return new[:m_new.start(1)] + m_old.group(1) + new[m_new.end(1):]


def generated_content(cfg: Config, today: dt.date) -> dict[str, str]:
    out = {"projects/_index.md": gen_projects_index(cfg, today),
           "wiki/_index.md": gen_wiki_index(cfg, today)}
    out.update(gen_wiki_domain_pages(cfg, today))
    out["Home.md"] = gen_home(cfg, today)          # last: reads the others' inputs
    return out


def orphaned_generated(cfg: Config, wanted: set[str]) -> tuple[list[str], list[str]]:
    """Generated files that no longer correspond to anything in the config.

    Removing a domain should remove its router page — otherwise the vault keeps a
    page for a category that no longer exists. Only files carrying the generated
    marker are eligible: a file someone hand-wrote into that folder is theirs, and
    deleting it because a config value changed would be the kind of surprise this
    system exists to avoid.

    Returns (removable, foreign).
    """
    removable, foreign = [], []
    domain_dir = VAULT / cfg.wiki_domain_dir
    if not domain_dir.is_dir():
        return removable, foreign
    for p in sorted(domain_dir.glob("*.md")):
        relpath = rel(p)
        if relpath in wanted or p.name.startswith("_"):
            continue
        (removable if GENERATED_MARK in read_text(p) else foreign).append(relpath)
    return removable, foreign


def cmd_index(cfg: Config, args) -> int:
    today = dt.date.today()
    content_by_path = generated_content(cfg, today)
    changed = []
    for relpath, content in content_by_path.items():
        p = VAULT / relpath
        old = read_text(p) if p.exists() else ""
        content = _preserve_prose(old, content)
        if old != content:
            if not args.check:
                atomic_write(p, content)
            changed.append(relpath)

    removable, foreign = orphaned_generated(cfg, set(content_by_path))
    if args.check:
        for c in changed:
            print(f"STALE  {c}")
        for c in removable:
            print(f"ORPHAN {c}: no longer in the config — run `vault.py index`")
        return 1 if (changed or removable) else 0

    for relpath in removable:
        (VAULT / relpath).unlink()
    for relpath in foreign:
        print(f"WARN   {relpath} is not a current domain page but was not generated "
              f"— left alone. Move or delete it by hand.")
    if not args.quiet:
        parts = []
        if changed:
            parts.append(f"{len(changed)} regenerated: " + ", ".join(changed))
        if removable:
            parts.append(f"{len(removable)} removed: " + ", ".join(removable))
        print("index: " + ("; ".join(parts) if parts else "all current"))
    return 0


def generated_stale(cfg: Config, today: dt.date) -> list[str]:
    content_by_path = generated_content(cfg, today)
    stale = []
    for relpath, content in content_by_path.items():
        p = VAULT / relpath
        old = read_text(p) if p.exists() else ""
        if old != _preserve_prose(old, content):
            stale.append(f"{relpath}: stale — run `python3 scripts/vault.py index`")
    removable, _ = orphaned_generated(cfg, set(content_by_path))
    stale += [f"{r}: generated page for a domain that no longer exists — "
              f"run `python3 scripts/vault.py index`" for r in removable]
    return stale


# ------------------------------------------------------------------ status

def collect_status(cfg: Config, today: dt.date) -> dict:
    """Every fact the weekly review and the dashboard need, computed once."""
    st: dict = {}

    itype = cfg.types.get("inbox")
    inbox = list(iter_notes(cfg, [itype.folder])) if itype else []
    ages = [days_since(p.name[:10], today) for p in inbox]
    ages = [a for a in ages if a is not None]
    st["inbox"] = {"count": len(inbox), "oldest_days": max(ages) if ages else None,
                   "files": [rel(p) for p in inbox[:20]]}

    ptype = cfg.types["project"]
    by_status: Counter = Counter()
    stale, old_ideas, awaiting = [], [], []
    for p, fm in _collect(cfg, ptype.folder):
        status = fm_str(fm.get("status")) or "active"
        by_status[status] += 1
        age = days_since(fm.get("updated"), today)
        if status == "active" and age is not None and age > cfg.stale_active_days:
            stale.append(p.stem)
        if status == "idea" and age is not None and age > cfg.stale_idea_days:
            old_ideas.append(p.stem)
        if status == "done":
            awaiting.append(p.stem)
    st["projects"] = {"by_status": dict(by_status), "stale": sorted(stale),
                      "old_ideas": sorted(old_ideas), "awaiting_archive": sorted(awaiting)}

    atype = cfg.types.get("area")
    areas = list(_collect(cfg, atype.folder)) if atype else []
    st["areas"] = {"active": sum(1 for _, fm in areas if fm_str(fm.get("status")) == "active"),
                   "dormant": sum(1 for _, fm in areas if fm_str(fm.get("status")) == "dormant")}

    due = []
    dec = cfg.find_variant("decision")
    if dec:
        for p, fm in _collect(cfg, dec.folder):
            if fm_str(fm.get("outcome")) != "unknown" or fm_str(fm.get("status")) == "superseded":
                continue
            deadline = fm.get("review_on") or fm.get("date")
            age = days_since(deadline, today)
            if age is not None and age >= (0 if fm.get("review_on") else cfg.decision_review_days):
                due.append(p.stem)
    st["decisions"] = {"due": sorted(due)}

    wtype = cfg.types["wiki"]
    week_ago = today - dt.timedelta(days=7)
    wiki = [(p, fm) for p, fm in _collect(cfg, wtype.folder)
            if not rel(p).startswith(cfg.wiki_domain_dir + "/")]
    new_week = [p.stem for p, fm in wiki
                if (d := parse_date(fm.get("created"))) and d >= week_ago]
    st["wiki"] = {"total": len(wiki), "created_this_week": sorted(new_week)}

    stype = cfg.types.get("source")
    st["sources"] = {"total": sum(1 for _ in _collect(cfg, stype.folder))} if stype else {"total": 0}
    st["people"] = sum(1 for _ in _collect(cfg, cfg.types["person"].folder)) if "person" in cfg.types else 0
    st["meetings"] = sum(1 for _ in _collect(cfg, cfg.types["meeting"].folder)) if "meeting" in cfg.types else 0

    tasks = collect_tasks(cfg, today)
    st["tasks"] = {"open": sum(len(v) for v in tasks.values()), "notes": len(tasks)}

    ltype = cfg.types.get("log")
    cadence: dict[str, int] = {}
    if ltype:
        for p in iter_notes(cfg, [ltype.folder]):
            m = re.match(r"^(\d{4}-\d{2}-\d{2})-(.+)\.md$", p.name)
            if not m:
                continue
            age = days_since(m.group(1), today)
            if age is not None:
                cadence[m.group(2)] = min(cadence.get(m.group(2), age), age)
    st["cadence"] = cadence
    return st


def collect_tasks(cfg: Config, today: dt.date, days: int = 30) -> dict[str, list[str]]:
    """Open checkboxes, from the notes that own them. Tasks are never their own note,
    so this is the only place they are ever aggregated."""
    out: dict[str, list[str]] = {}
    folders = [t.folder for name, t in cfg.types.items()
               if name in ("project", "area", "meeting", "daily")]
    cutoff = today - dt.timedelta(days=days)
    for p in iter_notes(cfg, folders):
        r = rel(p)
        if p.name.startswith("_"):
            continue
        if r.startswith(cfg.types["daily"].folder + "/"):
            d = parse_date(p.stem)
            if d and d < cutoff:
                continue
        ptype = cfg.type_for_path(r)
        if ptype and ptype.archive_folder and r.startswith(ptype.archive_folder + "/"):
            continue
        found = TASK_OPEN_RE.findall(fmlib.strip_code(read_text(p)))
        if found:
            out[r] = [t.strip() for t in found]
    return out


def cmd_status(cfg: Config, args) -> int:
    today = dt.date.today()
    st = collect_status(cfg, today)
    if args.json:
        print(json.dumps(st, indent=2, sort_keys=True))
        return 0

    print(f"== {cfg.name} · {today.isoformat()} ==\n")
    oldest = st["inbox"]["oldest_days"]
    print(f"Inbox            {st['inbox']['count']}"
          + (f" (oldest {oldest}d)" if oldest is not None else ""))
    by = st["projects"]["by_status"]
    print("Projects         " + (" · ".join(f"{k} {v}" for k, v in sorted(by.items())) or "none"))
    print(f"Areas            active {st['areas']['active']} · dormant {st['areas']['dormant']}")
    print(f"Knowledge        {st['wiki']['total']} wiki · {st['sources']['total']} sources"
          f" · {len(st['wiki']['created_this_week'])} new this week")
    print(f"Tasks            {st['tasks']['open']} open across {st['tasks']['notes']} note(s)")
    if st["cadence"]:
        print("Last runs        " + " · ".join(f"{k} {v}d ago"
                                               for k, v in sorted(st["cadence"].items())))

    flagged = False
    for label, items in ((f"Stale active (>{cfg.stale_active_days}d)", st["projects"]["stale"]),
                         (f"Ideas older than {cfg.stale_idea_days}d", st["projects"]["old_ideas"]),
                         ("Done, awaiting archive", st["projects"]["awaiting_archive"]),
                         ("Decisions due for outcome", st["decisions"]["due"])):
        if not items:
            continue
        if not flagged:
            print("\n-- needs a decision --")
            flagged = True
        # A wall of eighty names is not a review queue, it is wallpaper. Show a
        # handful; `--json` carries the full list for anything that wants it.
        shown = ", ".join(items[:8])
        more = f" … and {len(items) - 8} more" if len(items) > 8 else ""
        print(f"{label} ({len(items)}): {shown}{more}")
    return 0


def cmd_tasks(cfg: Config, args) -> int:
    today = dt.date.today()
    tasks = collect_tasks(cfg, today, days=10_000 if args.all else 30)
    if args.json:
        print(json.dumps(tasks, indent=2, sort_keys=True))
        return 0
    if not tasks:
        print("No open tasks.")
        return 0
    for note in sorted(tasks):
        print(f"\n{note}")
        for t in tasks[note]:
            print(f"  - [ ] {t}")
    print(f"\n{sum(len(v) for v in tasks.values())} open task(s) in {len(tasks)} note(s)")
    return 0


# ------------------------------------------------------------------ check / doctor

def cmd_lint(cfg: Config, args) -> int:
    paths = [Path(p) for p in args.paths] if args.paths else list(iter_notes(cfg))
    issues = linter.lint_paths(paths, cfg)
    for issue in sorted(issues, key=lambda i: (i.path, i.line)):
        print(issue)
    blocking = [i for i in issues if i.blocking]
    print(f"\nlint: {len(blocking)} blocking, {len(issues) - len(blocking)} minor")
    return 1 if blocking else 0


def cmd_check(cfg: Config, args) -> int:
    today = dt.date.today()
    issues = [i for p in iter_notes(cfg) for i in linter.lint_file(p, cfg, text=read_text(p))]
    errors = [str(i) for i in issues if i.blocking]
    warnings = [str(i) for i in issues if not i.blocking]

    struct_err, struct_warn = structure_issues(cfg)
    errors += struct_err
    warnings += struct_warn
    warnings += duplicate_basenames(cfg)
    errors += generated_stale(cfg, today)

    src_err, src_dangling = source_link_issues(cfg)
    errors += src_err
    if src_dangling:
        warnings.append(f"{len(src_dangling)} wiki sources: entries resolve to nothing "
                        f"— list with `vault.py doctor`")

    broken, _ = link_report(cfg)
    n_broken = sum(broken.values())

    for e in errors:
        print(f"ERROR  {e}")
    for w in warnings:
        print(f"WARN   {w}")
    if n_broken:
        level = "ERROR" if args.strict else "WARN"
        print(f"{level:<6} {len(broken)} missing link target(s), {n_broken} occurrence(s) "
              f"— `python3 scripts/vault.py links`")
        if args.strict:
            errors.append("broken links")

    total_warn = len(warnings) + (1 if n_broken else 0)
    print(f"\nvault check: {len(errors)} error(s), {total_warn} warning(s)")
    return 1 if errors else 0


def cmd_links(cfg: Config, args) -> int:
    broken, where = link_report(cfg)
    if args.wanted:
        print("Most-linked pages that do not exist yet — good candidates to write:\n")
        for target, n in broken.most_common(args.top):
            print(f"{n:>4}  [[{target}]]   e.g. {where[target][0]}")
        return 0
    if not broken:
        print("No broken links.")
        return 0
    for target, n in broken.most_common():
        print(f"[[{target}]] — {n} link(s) from: {', '.join(where[target])}")
    print(f"\n{len(broken)} missing target(s), {sum(broken.values())} occurrence(s)")
    return 0


def cmd_doctor(cfg: Config, args) -> int:
    today = dt.date.today()
    rc = cmd_check(cfg, args)
    print("\n== advisory ==\n")

    # Orphans: notes nothing links to. A note nobody can reach is a note you will
    # never read again.
    idx = basename_index(cfg)
    inbound: Counter = Counter()
    for p in iter_notes(cfg):
        text = fmlib.strip_code(read_text(p))
        fm = parse_note(p)
        targets = set(fmlib.INLINE_LINK_RE.findall(text))
        for field in cfg.link_lists | cfg.link_scalars:
            for entry in fmlib.as_list(fm.get(field)):
                targets.add(str(entry))
        for raw in targets:
            inbound[fmlib.link_target(raw)] += 1

    orphan_folders = [t.folder for name, t in cfg.types.items()
                      if name in ("wiki", "project", "area", "person")]
    orphans = [rel(p) for p in iter_notes(cfg, orphan_folders)
               if not p.name.startswith("_") and not cfg.is_generated(rel(p))
               and inbound.get(p.stem, 0) == 0]
    print(f"Orphans (nothing links to them): {len(orphans)}")
    for o in sorted(orphans)[:15]:
        print(f"  {o}")
    if len(orphans) > 15:
        print(f"  … and {len(orphans) - 15} more")

    # Source coverage: a source that never reached a wiki page is a digest, not
    # knowledge. The trend matters more than the number.
    stype, wtype = cfg.types.get("source"), cfg.types.get("wiki")
    if stype and wtype:
        cited: set[str] = set()
        for p, fm in _collect(cfg, wtype.folder):
            for entry in fmlib.as_list(fm.get("sources")):
                cited.add(fmlib.link_target(str(entry)))
        sources = [p for p, _ in _collect(cfg, stype.folder)]
        uncited = [p for p in sources if p.stem not in cited]
        if sources:
            pct = 100 * (len(sources) - len(uncited)) // len(sources)
            print(f"\nSource coverage: {pct}% of {len(sources)} sources are cited by a wiki page")
            print(f"  {len(uncited)} uncited — reading you filed but never compiled")

    # Stale knowledge: pages nothing has re-confirmed in a long time.
    if wtype:
        stale = [p.stem for p, fm in _collect(cfg, wtype.folder)
                 if not rel(p).startswith(cfg.wiki_domain_dir + "/")
                 and (age := days_since(fm.get("last_corroborated") or fm.get("updated"), today))
                 and age > cfg.stale_wiki_days]
        print(f"\nWiki pages untouched for over {cfg.stale_wiki_days}d: {len(stale)}")
        for s in sorted(stale)[:10]:
            print(f"  {s}")

    _, dangling = source_link_issues(cfg)
    if dangling:
        print(f"\nDangling sources: entries ({len(dangling)})")
        for d in dangling[:10]:
            print(f"  {d}")

    unsafe = [rel(p) for p in iter_notes(cfg)
              if any(ch in SOFT_ILLEGAL for ch in p.stem) and not p.name.startswith("_")]
    if unsafe:
        print(f"\nLink-unsafe filenames ({len(unsafe)}) — fix with `vault.py rename`:")
        for u in unsafe[:10]:
            print(f"  {u}")

    missing_domain = [rel(p) for p, fm in _collect(cfg, cfg.types["wiki"].folder)
                      if not fm.get("domain")]
    if missing_domain:
        print(f"\nWiki pages with no domain ({len(missing_domain)})")
        for m in missing_domain[:10]:
            print(f"  {m}")
    return rc


# ------------------------------------------------------------------ new

MOMENT_TOKENS = [("YYYY", "%Y"), ("GGGG", "%G"), ("MMMM", "%B"), ("MM", "%m"),
                 ("DD", "%d"), ("dddd", "%A"), ("HH", "%H"), ("mm", "%M"),
                 ("WW", "%V"), ("ww", "%V"), ("[W]", "W")]


def render_template(text: str, title: str, when: dt.datetime, cfg: Config) -> str:
    """Expand Obsidian-style {{date:...}} / {{title}} placeholders.

    Templates quote every date placeholder so the file is valid YAML *before*
    rendering (Obsidian's own Templates plugin inserts into a live note). Fields
    the schema says are unquoted get unquoted here, after substitution."""
    def fmt(m):
        pattern = m.group(1)
        for token, py in MOMENT_TOKENS:
            pattern = pattern.replace(token, py)
        return when.strftime(pattern)

    text = re.sub(r"\{\{(?:date|time):([^}]+)\}\}", fmt, text)
    text = text.replace("{{date}}", when.strftime("%Y-%m-%d"))
    text = text.replace("{{time}}", when.strftime("%H:%M"))
    text = text.replace("{{title}}", title)
    text = text.replace("{{vault}}", cfg.name)
    unquoted = "|".join(sorted(cfg.dates_unquoted))
    return re.sub(rf'^({unquoted}): "(\d{{4}}-\d{{2}}-\d{{2}})"$', r"\1: \2",
                  text, flags=re.MULTILINE)


def resolve_new_kind(cfg: Config, kind: str):
    """`new` accepts a type name (`project`) or a variant name (`decision`, `paper`)."""
    if kind in cfg.types:
        t = cfg.types[kind]
        if t.variants:
            return None, None  # ambiguous: name the variant instead
        return t, None
    variant = cfg.find_variant(kind)
    if variant:
        return cfg.types[variant.parent], variant
    return None, None


def new_note_path(cfg: Config, ntype, variant, title: str, when: dt.datetime) -> Path:
    folder = variant.folder if variant else ntype.folder
    pattern = (variant.filename if variant and variant.filename else ntype.filename)
    safe = slugify(title)
    date = when.date().isoformat()
    if pattern == "daily":
        return VAULT / folder / when.strftime("%Y") / when.strftime("%m") / f"{date}.md"
    if pattern == "week":
        return VAULT / folder / f"{when.strftime('%G-W%V')}.md"
    if pattern == "capture":
        words = " ".join(safe.split()[:8]) or "Capture"
        return VAULT / folder / f"{date} {when.strftime('%H%M')} {words}.md"
    if pattern == "dated":
        return VAULT / folder / f"{date} {safe}.md"
    if pattern == "log":
        return VAULT / folder / f"{date}-{safe.lower().replace(' ', '-')}.md"
    return VAULT / folder / f"{safe}.md"


def apply_sets(cfg: Config, text: str, sets: list[str]) -> str:
    """Apply `--set key=value` to the rendered frontmatter, quoting per the schema."""
    m = fmlib.FRONTMATTER_RE.match(text)
    if not m:
        return text
    block, rest = m.group(1), text[m.end():]
    lines = block.split("\n")
    for item in sets:
        key, _, value = item.partition("=")
        key, value = key.strip(), value.strip()
        if not key:
            continue
        if key in cfg.link_lists:
            parts = [v.strip() for v in value.split(",") if v.strip()]
            rendered = "\n".join(f'  - "[[{fmlib.link_target(v)}]]"' for v in parts)
            new = f"{key}:\n{rendered}" if parts else f"{key}: []"
        elif key in cfg.link_scalars:
            new = f'{key}: "[[{fmlib.link_target(value)}]]"'
        elif key == "tags":
            parts = [v.strip() for v in value.split(",") if v.strip()]
            new = f"{key}: [{', '.join(parts)}]"
        elif key in cfg.dates_unquoted or value[:1] in ('"', "[") or value in ("true", "false"):
            new = f"{key}: {value}"
        elif key in cfg.dates_quoted or " " in value or ":" in value:
            new = f'{key}: "{value}"'
        else:
            new = f"{key}: {value}"
        for i, line in enumerate(lines):
            if re.match(rf"^{re.escape(key)}:", line):
                # Replace the key and any block-list items under it.
                j = i + 1
                while j < len(lines) and lines[j].startswith((" ", "\t")) and lines[j].lstrip().startswith("-"):
                    j += 1
                lines[i:j] = new.split("\n")
                break
        else:
            lines.append(new)
    return "---\n" + "\n".join(lines) + "\n---\n" + rest


def cmd_new(cfg: Config, args) -> int:
    ntype, variant = resolve_new_kind(cfg, args.type)
    if ntype is None:
        known = sorted([n for n, t in cfg.types.items() if not t.variants]
                       + list(cfg.all_variants))
        parent = cfg.types.get(args.type)
        hint = (f"{args.type!r} has variants — name one of: "
                f"{', '.join(sorted(parent.variants))}" if parent
                else f"unknown type {args.type!r}")
        print(f"{hint}.\nKnown: {', '.join(known)}", file=sys.stderr)
        return 2
    if ntype.immutable and not args.force:
        print(f"{ntype.name} notes are written by pipelines, not by hand "
              f"(docs/ingestion.md). Use --force if you are sure.", file=sys.stderr)
        return 2

    when = dt.datetime.now()
    if args.date:
        try:
            when = dt.datetime.combine(dt.date.fromisoformat(args.date), when.time())
        except ValueError:
            print(f"--date must be YYYY-MM-DD, got {args.date!r}", file=sys.stderr)
            return 2

    # Types whose filename is derived from the date name themselves.
    pattern = variant.filename if variant and variant.filename else ntype.filename
    self_naming = pattern in ("daily", "week")
    title = args.title or ((variant.name if variant else ntype.name).title()
                           if self_naming else "")
    if not title:
        print(f"a title is required for `new {args.type}`", file=sys.stderr)
        return 2

    template_name = (variant.template if variant and variant.template else ntype.template)
    if not template_name:
        template_name = f"{variant.name if variant else ntype.name}.md"
    tpl = VAULT / "templates" / template_name
    if not tpl.exists():
        print(f"missing template {rel(tpl)}", file=sys.stderr)
        return 2

    text = render_template(read_text(tpl), title, when, cfg)
    sets = list(args.set or [])
    if variant and ntype.variant_field:
        sets.insert(0, f"{ntype.variant_field}={variant.name}")
    if args.body:
        text = text.rstrip() + "\n\n" + args.body + "\n"
    text = apply_sets(cfg, text, sets)

    # A title that had to be sanitized keeps its pretty form as an alias, so
    # [[Original/Title]] still resolves.
    path = next_free_path(new_note_path(cfg, ntype, variant, title, when))
    if title and slugify(title) != title and "aliases:" not in text:
        text = apply_sets(cfg, text, [f'aliases=["{title}"]'])

    if path.exists() and not args.force:
        print(f"refusing to overwrite {rel(path)}", file=sys.stderr)
        return 2
    atomic_write(path, text)

    issues = linter.lint_file(path, cfg)
    blocking = [i for i in issues if i.blocking]
    print(rel(path), flush=True)
    for issue in blocking:
        print(f"  {issue.level}  {issue.msg}", file=sys.stderr)
    if blocking:
        print("\nFill the fields above, then re-run `vault.py lint <path>`.", file=sys.stderr)
        return 1
    return 0


# ------------------------------------------------------------------ rename

def cmd_rename(cfg: Config, args) -> int:
    src = Path(args.path)
    if not src.is_absolute():
        src = VAULT / args.path
    if not src.is_file():
        print(f"no such note: {args.path}", file=sys.stderr)
        return 2

    r = rel(src)
    ntype = cfg.type_for_path(r)
    if ntype is None:
        print(f"{r} is not in a content folder", file=sys.stderr)
        return 2
    if ntype.immutable and not args.force:
        print(f"{ntype.name} notes are immutable. Use --force if you must.", file=sys.stderr)
        return 2

    old_stem = src.stem
    prefix = ""
    m = re.match(r"^(\d{4}-\d{2}-\d{2} )", old_stem)
    if m and ntype.filename in ("dated", "capture"):
        prefix = m.group(1)
    new_stem = prefix + slugify(args.new_title)
    if new_stem == old_stem:
        print("name unchanged")
        return 0
    dst = src.with_name(new_stem + ".md")
    if dst.exists():
        print(f"target already exists: {rel(dst)}", file=sys.stderr)
        return 2

    edits: list[tuple[Path, str]] = []
    pattern = re.compile(r"\[\[" + re.escape(old_stem) + r"((?:#|\|)[^\]]*)?\]\]")
    for p in iter_notes(cfg):
        text = read_text(p)
        new_text, n = pattern.subn(lambda mm: f"[[{new_stem}{mm.group(1) or ''}]]", text)
        if n:
            edits.append((p, new_text))

    print(f"{r}  ->  {rel(dst)}")
    print(f"{len(edits)} file(s) contain links to update")
    if args.dry_run:
        for p, _ in edits[:20]:
            print(f"  {rel(p)}")
        print("\n(dry run — nothing written)")
        return 0

    for p, new_text in edits:
        atomic_write(p, new_text)
    src.rename(dst)

    # `title:` follows the filename, and the old name survives as an alias so links
    # from outside the vault — and your own memory — keep resolving.
    text = read_text(dst)
    fm = fmlib.parse(text)
    sets = []
    if "title" in fm:
        sets.append(f"title={args.new_title}")
    if not args.no_alias:
        aliases = [str(a) for a in fmlib.as_list(fm.get("aliases"))]
        old_title = fmlib.unquote(str(fm.get("title", ""))) or old_stem
        for candidate in (old_stem, old_title):
            if candidate and candidate not in aliases and candidate != args.new_title \
                    and not DATE_PREFIX_RE.match(candidate):
                aliases.append(candidate)
        if aliases:
            quoted = ", ".join(chr(34) + a + chr(34) for a in aliases)
            sets.append(f"aliases=[{quoted}]")
    if sets:
        atomic_write(dst, apply_sets(cfg, text, sets))
    print("done. Run `python3 scripts/vault.py check`.")
    return 0


# ------------------------------------------------------------------ docs

def cmd_docs(cfg: Config, args) -> int:
    import gen_schema_doc
    text = gen_schema_doc.render(cfg)
    path = VAULT / "docs" / "schema.md"
    old = read_text(path) if path.exists() else ""
    if old == text:
        print("docs/schema.md: current")
        return 0
    if args.check:
        print("STALE  docs/schema.md — run `python3 scripts/vault.py docs`")
        return 1
    atomic_write(path, text)
    print("docs/schema.md: regenerated from config/lifeos.toml")
    return 0


# ------------------------------------------------------------------ main

def main(argv=None) -> int:
    ap = argparse.ArgumentParser(prog="vault.py", description=__doc__.split("\n")[0])
    sub = ap.add_subparsers(dest="cmd", required=True)

    s = sub.add_parser("check", help="structure + schema + generated freshness")
    s.add_argument("--strict", action="store_true", help="treat broken links as errors")
    s = sub.add_parser("lint", help="frontmatter only")
    s.add_argument("paths", nargs="*")
    s = sub.add_parser("links", help="broken wikilinks")
    s.add_argument("--wanted", action="store_true", help="most-linked missing pages")
    s.add_argument("--top", type=int, default=30)
    s = sub.add_parser("index", help="regenerate generated views")
    s.add_argument("--check", action="store_true", help="report staleness, write nothing")
    s.add_argument("--quiet", action="store_true")
    s = sub.add_parser("status", help="what needs attention")
    s.add_argument("--json", action="store_true")
    s = sub.add_parser("tasks", help="open checkboxes")
    s.add_argument("--all", action="store_true", help="include old daily notes")
    s.add_argument("--json", action="store_true")
    s = sub.add_parser("doctor", help="check + advisory report")
    s.add_argument("--strict", action="store_true")
    s = sub.add_parser("new", help="create a note with correct path and frontmatter")
    s.add_argument("type")
    s.add_argument("title", nargs="?")
    s.add_argument("--set", action="append", metavar="KEY=VALUE")
    s.add_argument("--body", help="text to append below the frontmatter")
    s.add_argument("--date", help="YYYY-MM-DD (default: today)")
    s.add_argument("--force", action="store_true")
    s = sub.add_parser("rename", help="rename one note and rewrite links to it")
    s.add_argument("path")
    s.add_argument("new_title")
    s.add_argument("--dry-run", action="store_true")
    s.add_argument("--no-alias", action="store_true", help="do not keep the old title as an alias")
    s.add_argument("--force", action="store_true")
    s = sub.add_parser("docs", help="regenerate docs/schema.md from config")
    s.add_argument("--check", action="store_true")

    args = ap.parse_args(argv)
    try:
        cfg = load()
    except ConfigError as e:
        print(f"ERROR  {e}", file=sys.stderr)
        return 2

    handlers = {"check": cmd_check, "lint": cmd_lint, "links": cmd_links, "index": cmd_index,
                "status": cmd_status, "tasks": cmd_tasks, "doctor": cmd_doctor,
                "new": cmd_new, "rename": cmd_rename, "docs": cmd_docs}
    return handlers[args.cmd](cfg, args)


if __name__ == "__main__":
    sys.exit(main())
